# Generated by Django 2.2.3 on 2019-07-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=31, unique=True, verbose_name='username'),
        ),
    ]
