# Generated by Django 2.2.3 on 2019-08-08 09:14

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190808_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First and last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Phone confirmed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unconfirmed_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Unconfirmed email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unconfirmed_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Unconfirmed phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='Username'),
        ),
    ]
